package.path = "./?.lua;" .. package.path
local p = require("parse")
local s, t = p.parse("Once upon a time")
assert(s == "Once upon a time" and t == nil)
s, t = p.parse("The end.achieved tok/s: 6.060789\n")
assert(s == "The end." and math.abs(t - 6.060789) < 1e-9, s)
s, t = p.parse("Lily smiled.\nachieved tok/s: 12")
assert(s == "Lily smiled." and t == 12)
assert(p.settled("I saw a") == "I saw ")
assert(p.settled("The end.\nachieved tok/") == "The end.\n")
assert(p.settled("The end.\nachieved tok/s: ") == "The end.\n")
s, t = p.settled("The end.\nachieved tok/s: 5.5\n")
assert(s == "The end." and t == 5.5)
assert(p.settled("caf\195") == "caf")
assert(p.settled("caf\195\169") == "caf\195\169")
assert(p.settled("\226\130") == "")
assert(p.settled("") == "")
print("parse ok")
